spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url:jdbc:postgresql://localhost:5432/mandalart}
    username: ${db_username:postgres}
    password: ${db_password:1234}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: ${db.ddl:update}
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: true
    open-in-view: false

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 30
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true
